DiplomProject/WebSite/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebSite.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
    }
}

DiplomProject/WebSite/Controllers/LogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSite.EntityFramework;
using Microsoft.AspNet.Identity;
using InternalDAL;
using WebSite.Models.Log;
using System.Globalization;

namespace WebSite.Controllers
{
    [Authorize(Roles = "Client")]
    public class LogController : BaseController
    {
        public ActionResult Visits()
        {
            string userID = this.User.Identity.GetUserId();

            AspNetUser user = DB.AspNetUsers.Find(userID);
            IEnumerable<EntranceHistoryItemModel> model = new List<EntranceHistoryItemModel>();
            if (user != null)
            {
                List<EntranceHistory> entranceHistories = new List<EntranceHistory>();
                foreach (Card card in user.Cards)
                {
                    entranceHistories.AddRange(card.EntranceHistories);
                }

                model = entranceHistories.OrderBy(entranceHistory => entranceHistory.CreatedAt).
                    Select(entranceHistory => new EntranceHistoryItemModel
                {
                    UserName = EntityHelper.GetFullName(user.Id),
                    Date = entranceHistory.CreatedAt.HasValue ? entranceHistory.CreatedAt.Value.ToString("dd/MM/yyyy", CultureInfo.InvariantCulture) : String.Empty,
                    Time = entranceHistory.CreatedAt.HasValue ? entranceHistory.CreatedAt.Value.ToString("hh:mm", CultureInfo.InvariantCulture) : String.Empty,
                    CardNumber = entranceHistory.Card.CardId,
                    EntryStatus = entranceHistory.EntryStatus,
                    FacilityName = entranceHistory.Facility.Name,
                }).ToList();
            }

            return View(model);
        }

        public ActionResult Payments()
        {
            string userID = this.User.Identity.GetUserId();

            AspNetUser user = DB.AspNetUsers.Find(userID);
            IEnumerable<PaymentHistoryItemModel> model = new List<PaymentHistoryItemModel>();
            if (user != null)
            {
                model = user.PaymentHistories.OrderBy(paymentHistory => paymentHistory.CreatedAt).Select(paymentHistory => new PaymentHistoryItemModel
                {
                    Date = paymentHistory.CreatedAt.HasValue ? paymentHistory.CreatedAt.Value.ToString("dd/MM/yyyy", CultureInfo.InvariantCulture) : String.Empty,
                    Time = paymentHistory.CreatedAt.HasValue ? paymentHistory.CreatedAt.Value.ToString("hh:mm", CultureInfo.InvariantCulture) : String.Empty,
                    IssuerName = EntityHelper.GetFullName(paymentHistory.IssuerId),
                    RecepientName = EntityHelper.GetFullName(paymentHistory.RecepientId),
                    ProductName = paymentHistory.Product.Name,
                    PayPalEmail = paymentHistory.PayPalEmail
                }).ToList();
            }

            return View(model);
        }
    }
}

DiplomProject/WebSite/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@using WebSite.Models.Subscription
@using WebSite.Controllers

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - @Resources.ApplicationName</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top shadow">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink(Resources.ApplicationName, "Index", "Home", null, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink(Resources.About, "About", "Home")</li>
                        <li>@Html.ActionLink(Resources.Contact, "Contact", "Home")</li>
                        @if (Request.IsAuthenticated)
                        {
                            if (this.User.IsInRole("Client"))
                            { 
                                <li>@Html.ActionLink(Resources.VisitsLog, "Visits", "Log")</li>
                                <li>@Html.ActionLink(Resources.PaymentsLog, "Payments", "Log")</li>
                            }
                            if(this.User.IsInRole("Administrator"))
                            { 
                                <li>@Html.ActionLink(Resources.AdminPanel, "Index", "Admin")</li>
                            }
                            if (this.User.IsInRole("Administrator") || this.User.IsInRole("FacilityManager") || this.User.IsInRole("Receptionist"))
                            {
                                <li>@Html.ActionLink(Resources.ManagerPanel, "Index", "Manage")</li>
                            }
                        }
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content shadow">
            @RenderBody()

            <div class="footer-wrapper">
                <hr />
                <footer class="centercontents">
                    <p class="pull-left">&copy; @DateTime.Now.Year - @Resources.ApplicationName</p>

                    @if (Request.IsAuthenticated)
                    {
                            SubscriptionCreditsModel model = (new SubscriptionController()).GetSubscriptionCredits(User.Identity.GetUserId());

                        if (model != null && this.ViewContext.RouteData.GetRequiredString("controller") != "Subscription")
                        {
                            <span class="span5 center">
                                @if (!model.UnlimitedAccess)
                                {
                                    if (model.ActiveUntil.HasValue && model.ActiveUntil.Value > DateTime.Today)
                                    {
                                        @Html.ActionLink(Resources.ActiveUntil + " " + (model.ActiveUntil.HasValue ? model.ActiveUntil.Value.ToString("dd/MM/yyyy") : "--/--/----"), "Index", "Subscription")
                                    }
                                    else
                                    {
                                        @Html.ActionLink(Resources.NoActiveSubsription, "Index", "Subscription", new { }, new { style = "color: red;" })
                                    }
                                    <span>|</span>
                                    if (model.Credits > 0)
                                    {
                                        @Html.ActionLink(Resources.Credits + " " + model.Credits, "Index", "Subscription")
                                    }
                                    else
                                    {
                                        @Html.ActionLink(Resources.Credits + " " + model.Credits, "Index", "Subscription", new { }, new { style = "color: red;" })
                                    }
                                }
                                else
                                {
                                    @Html.ActionLink(Resources.UnlimitedAccess, "Index", "Subscription")
                                }
                            </span>
                        }
                    }



                    <span class="language-control pull-right">
                        @Html.ActionLink(Resources.Bulgarian, "SetCulture", "Home", new { culture = "bg" }, new { @class = "btn btn-default" })
                        @Html.ActionLink(Resources.English, "SetCulture", "Home", new { culture = "en" }, new { @class = "btn btn-default" })
                    </span>
                </footer>
            </div>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/knockout")
        @RenderSection("scripts", required: false)
    </body>

</html>